# Generated by Django 3.0.8 on 2020-09-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200824_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='charged',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
