# Generated by Django 3.0.8 on 2021-04-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200906_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='isVerified_notes',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
